// Generated by CoffeeScript 1.10.0
(function() {
  var BrowserWindow, app, electron, mainWindow;

  electron = require('electron');

  app = electron.app;

  BrowserWindow = electron.BrowserWindow;

  mainWindow = void 0;

  app.on('ready', function() {
    mainWindow = new BrowserWindow({
      width: 800,
      height: 600
    });
    mainWindow.loadURL('file://' + __dirname + '/public/index.html');
    mainWindow.webContents.openDevTools();
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  });

}).call(this);
